#!/usr/bin/php
<?php

if ( ! isset( $argv[1] ) ) {
	echo( 'Usage: relwords <phrase>' );
	die();
}

$orig_phrase = join( ' ', array_slice( $argv, 1 ) );

$phrase = str_replace( ' ', '+', $orig_phrase );

echo( 'Looking up words that have the same meaning as "' . $orig_phrase . "\" \n\r" );

$same_meaning = getWordsWithSameMeaning( $phrase, 100 );

$shortlist = array_slice( $same_meaning, 0, 100 );

$i = 0;
$maxlength = 0;

foreach ( $shortlist as $word_item ) {
	$maxlength = max( $maxlength, strlen( $word_item['word'] ) + 2 );
}

foreach ( $shortlist as $word_item ) {
	if ( $i % 2 == 0 ) {
		$rendered = str_pad( $word_item['word'], $maxlength );
	} elseif ( $i % 2 == 1 ) {
		$rendered = $word_item['word'] . "\n\r";
	}

	echo $rendered;
	$i++;
}

function getWordsWithSameMeaning( $phrase, $num = 5 ) {
	// get word with same meaning
	$url = 'https://api.datamuse.com/words?ml=' . $phrase;

	$related = json_decode( file_get_contents( $url ), true );

	return array_slice( $related, 0, $num );
}
